.PHONY: clean All

All:
	@echo "----------Building project:[ BasicIO - Debug ]----------"
	@cd "C:\Users\randy\Documents\GIT\Udemy\CPP\Completed Code\Section05\BasicIO" && "$(MAKE)" -f  "BasicIO.mk"
clean:
	@echo "----------Cleaning project:[ BasicIO - Debug ]----------"
	@cd "C:\Users\randy\Documents\GIT\Udemy\CPP\Completed Code\Section05\BasicIO" && "$(MAKE)" -f  "BasicIO.mk" clean
